name: 'Read File'
description: 'Read a file'
inputs:
  filepath:
    required: true
    type: string

outputs:
  content:
    description: "File Content"
    value: ${{ steps.read-file-step.outputs.content }}
    
runs:
  using: "composite"
  steps:
    - id: read-file-step
      shell: bash
      run: |
        file_content=`cat ${{ inputs.filepath }}`
        file_content="${readme_content//'%'/'%25'}"
        file_content="${file_content//$'\n'/'%0A'}"
        file_content="${file_content//$'\r'/'%0D'}"
        echo $file_content
        echo $file_content
        echo $file_content
        echo "::set-output name=content::${file_content}"
    - name: Print out
      id: print
      shell: bash
      run: |          
        echo "${{ steps.read-file-step.outputs.content }}"           
        
     
