# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: ls -laR ./.github/workflows/
      - name: Read README file
        id: read-readme
        run: |
          readme_content=`cat README.md`
          readme_content="${readme_content//'%'/'%25'}"
          readme_content="${readme_content//$'\n'/'%0A'}"
          readme_content="${readme_content//$'\r'/'%0D'}"
          echo "::set-output name=readme::${readme_content}"
        
